{"uuid": "1c9f9a8c-50d3-422f-ba2e-2d13c9fab4cf", "children": ["191d5eea-6d3a-412a-be18-ec624310aa4f"], "befores": [{"name": "driver_get", "status": "passed", "start": 1586880352249, "stop": 1586880357488}], "afters": [{"name": "driver_get::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\n\n", "trace": "  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\_pytest\\fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\Documentos\\Development\\Automation\\tests\\tests.py\", line 20, in driver_get\n    web_driver.close()\n  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1586880380893, "stop": 1586880380951}], "start": 1586880352249, "stop": 1586880380951}