{"uuid": "71a97ed8-499d-4317-b807-38d340522239", "children": ["22fde5b1-889c-4fe9-9858-177816a22c20", "46cb11dd-476e-4dca-851d-8d3639d1e172"], "befores": [{"name": "driver_init", "status": "passed", "start": 1584652395537, "stop": 1584652401191}], "afters": [{"name": "driver_init::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\n\n", "trace": "  File \"d:\\documentos\\development\\automation\\selenium\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"d:\\documentos\\development\\automation\\selenium\\lib\\site-packages\\_pytest\\fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\Documentos\\Development\\Automation\\tests\\tests.py\", line 29, in driver_init\n    web_driver.close()\n  File \"d:\\documentos\\development\\automation\\selenium\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"d:\\documentos\\development\\automation\\selenium\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\documentos\\development\\automation\\selenium\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1584652451530, "stop": 1584652451560}], "start": 1584652395537, "stop": 1584652451561}