{"uuid": "3e802c9f-56b5-4ca0-b7e0-db1689393427", "children": ["dce80cb5-7cff-4389-8799-701489f42a7a"], "befores": [{"name": "driver_init", "status": "passed", "start": 1586880013711, "stop": 1586880019391}], "afters": [{"name": "driver_init::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\n\n", "trace": "  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\_pytest\\fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\Documentos\\Development\\Automation\\tests\\tests.py\", line 29, in driver_init\n    web_driver.close()\n  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1586880050604, "stop": 1586880050631}], "start": 1586880013711, "stop": 1586880050631}