{"uuid": "a666793e-abf2-470a-b183-8a76c6d467b2", "children": ["6c0bd49e-c859-4af4-9dbd-a8ee6b08cbf0", "14f0ca94-c9c6-4716-af1e-423b98da2d81"], "befores": [{"name": "driver_init", "status": "passed", "start": 1584652643194, "stop": 1584652648324}], "afters": [{"name": "driver_init::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\n\n", "trace": "  File \"d:\\documentos\\development\\automation\\selenium\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"d:\\documentos\\development\\automation\\selenium\\lib\\site-packages\\_pytest\\fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\Documentos\\Development\\Automation\\tests\\tests.py\", line 29, in driver_init\n    web_driver.close()\n  File \"d:\\documentos\\development\\automation\\selenium\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"d:\\documentos\\development\\automation\\selenium\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\documentos\\development\\automation\\selenium\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1584652692639, "stop": 1584652692641}], "start": 1584652643194, "stop": 1584652692641}