{"uuid": "16555065-32c2-4036-9d23-d85377fdfa5e", "children": ["344d143e-881d-4597-922d-7ede875b590e"], "befores": [{"name": "driver_init", "status": "passed", "start": 1586880273124, "stop": 1586880278298}], "afters": [{"name": "driver_init::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\n\n", "trace": "  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\_pytest\\fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\Documentos\\Development\\Automation\\tests\\tests.py\", line 29, in driver_init\n    web_driver.close()\n  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1586880301940, "stop": 1586880302009}], "start": 1586880273124, "stop": 1586880302009}