{"uuid": "d4c6b0b3-9419-46b2-bbd6-a3938f3fd5aa", "children": ["883ac5ec-40b7-45a7-a37b-fb29cfa71add"], "befores": [{"name": "driver_init", "status": "passed", "start": 1586880950814, "stop": 1586880954533}], "afters": [{"name": "driver_init::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\n\n", "trace": "  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\_pytest\\fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\Documentos\\Development\\Automation\\tests\\tests.py\", line 29, in driver_init\n    web_driver.close()\n  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\documentos\\development\\automation\\virtual-environment\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1586880977978, "stop": 1586880978020}], "start": 1586880950814, "stop": 1586880978020}